[2024-11-25T07:37:01.764+0000] {processor.py:186} INFO - Started process (PID=198) to work on /opt/airflow/dags/mongo_test.py
[2024-11-25T07:37:01.765+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mongo_test.py for tasks to queue
[2024-11-25T07:37:01.766+0000] {logging_mixin.py:190} INFO - [2024-11-25T07:37:01.766+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_test.py
[2024-11-25T07:37:01.775+0000] {logging_mixin.py:190} INFO - [2024-11-25T07:37:01.771+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mongo_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_test.py", line 38, in <module>
    mongo_uri = Variable.get("MONGO_URI")
                ^^^^^^^^
NameError: name 'Variable' is not defined. Did you mean: 'callable'?
[2024-11-25T07:37:01.778+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_test.py
[2024-11-25T07:37:01.802+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mongo_test.py took 0.044 seconds
[2024-11-25T07:37:32.196+0000] {processor.py:186} INFO - Started process (PID=201) to work on /opt/airflow/dags/mongo_test.py
[2024-11-25T07:37:32.200+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mongo_test.py for tasks to queue
[2024-11-25T07:37:32.201+0000] {logging_mixin.py:190} INFO - [2024-11-25T07:37:32.200+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_test.py
[2024-11-25T07:37:32.209+0000] {logging_mixin.py:190} INFO - [2024-11-25T07:37:32.206+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mongo_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_test.py", line 38, in <module>
    mongo_uri = Variable.get("MONGO_URI")
                ^^^^^^^^
NameError: name 'Variable' is not defined. Did you mean: 'callable'?
[2024-11-25T07:37:32.211+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_test.py
[2024-11-25T07:37:32.242+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mongo_test.py took 0.053 seconds
[2024-11-25T07:38:02.765+0000] {processor.py:186} INFO - Started process (PID=204) to work on /opt/airflow/dags/mongo_test.py
[2024-11-25T07:38:02.766+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mongo_test.py for tasks to queue
[2024-11-25T07:38:02.767+0000] {logging_mixin.py:190} INFO - [2024-11-25T07:38:02.767+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_test.py
[2024-11-25T07:38:02.776+0000] {logging_mixin.py:190} INFO - [2024-11-25T07:38:02.774+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mongo_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_test.py", line 38, in <module>
    mongo_uri = Variable.get("MONGO_URI")
                ^^^^^^^^
NameError: name 'Variable' is not defined. Did you mean: 'callable'?
[2024-11-25T07:38:02.779+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_test.py
[2024-11-25T07:38:02.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mongo_test.py took 0.049 seconds
[2024-11-25T07:38:33.175+0000] {processor.py:186} INFO - Started process (PID=207) to work on /opt/airflow/dags/mongo_test.py
[2024-11-25T07:38:33.177+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mongo_test.py for tasks to queue
[2024-11-25T07:38:33.178+0000] {logging_mixin.py:190} INFO - [2024-11-25T07:38:33.177+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_test.py
[2024-11-25T07:38:33.186+0000] {logging_mixin.py:190} INFO - [2024-11-25T07:38:33.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mongo_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_test.py", line 38, in <module>
    mongo_uri = Variable.get("MONGO_URI")
                ^^^^^^^^
NameError: name 'Variable' is not defined. Did you mean: 'callable'?
[2024-11-25T07:38:33.188+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_test.py
[2024-11-25T07:38:33.217+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mongo_test.py took 0.049 seconds
[2024-11-25T07:39:03.586+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/mongo_test.py
[2024-11-25T07:39:03.587+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mongo_test.py for tasks to queue
[2024-11-25T07:39:03.588+0000] {logging_mixin.py:190} INFO - [2024-11-25T07:39:03.588+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_test.py
[2024-11-25T07:39:03.597+0000] {logging_mixin.py:190} INFO - [2024-11-25T07:39:03.594+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mongo_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_test.py", line 38, in <module>
    mongo_uri = Variable.get("MONGO_URI")
                ^^^^^^^^
NameError: name 'Variable' is not defined. Did you mean: 'callable'?
[2024-11-25T07:39:03.599+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_test.py
[2024-11-25T07:39:03.627+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mongo_test.py took 0.047 seconds
[2024-11-25T07:39:34.153+0000] {processor.py:186} INFO - Started process (PID=213) to work on /opt/airflow/dags/mongo_test.py
[2024-11-25T07:39:34.154+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mongo_test.py for tasks to queue
[2024-11-25T07:39:34.155+0000] {logging_mixin.py:190} INFO - [2024-11-25T07:39:34.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_test.py
[2024-11-25T07:39:34.162+0000] {logging_mixin.py:190} INFO - [2024-11-25T07:39:34.160+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mongo_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_test.py", line 38, in <module>
    mongo_uri = Variable.get("MONGO_URI")
                ^^^^^^^^
NameError: name 'Variable' is not defined. Did you mean: 'callable'?
[2024-11-25T07:39:34.165+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_test.py
[2024-11-25T07:39:34.195+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mongo_test.py took 0.050 seconds
[2024-11-25T07:40:04.743+0000] {processor.py:186} INFO - Started process (PID=216) to work on /opt/airflow/dags/mongo_test.py
[2024-11-25T07:40:04.744+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mongo_test.py for tasks to queue
[2024-11-25T07:40:04.746+0000] {logging_mixin.py:190} INFO - [2024-11-25T07:40:04.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_test.py
[2024-11-25T07:40:04.754+0000] {logging_mixin.py:190} INFO - [2024-11-25T07:40:04.751+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mongo_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_test.py", line 38, in <module>
    mongo_uri = Variable.get("MONGO_URI")
                ^^^^^^^^
NameError: name 'Variable' is not defined. Did you mean: 'callable'?
[2024-11-25T07:40:04.756+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_test.py
[2024-11-25T07:40:04.782+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mongo_test.py took 0.049 seconds
[2024-11-25T07:40:35.327+0000] {processor.py:186} INFO - Started process (PID=219) to work on /opt/airflow/dags/mongo_test.py
[2024-11-25T07:40:35.328+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mongo_test.py for tasks to queue
[2024-11-25T07:40:35.329+0000] {logging_mixin.py:190} INFO - [2024-11-25T07:40:35.329+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_test.py
[2024-11-25T07:40:35.519+0000] {logging_mixin.py:190} INFO - [2024-11-25T07:40:35.513+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mongo_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_test.py", line 38, in <module>
    mongo_uri = Variable.get("MONGO_URI")
                ^^^^^^^^
NameError: name 'Variable' is not defined. Did you mean: 'callable'?
[2024-11-25T07:40:35.523+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_test.py
[2024-11-25T07:40:35.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mongo_test.py took 0.234 seconds
[2024-11-25T07:41:06.039+0000] {processor.py:186} INFO - Started process (PID=222) to work on /opt/airflow/dags/mongo_test.py
[2024-11-25T07:41:06.041+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mongo_test.py for tasks to queue
[2024-11-25T07:41:06.042+0000] {logging_mixin.py:190} INFO - [2024-11-25T07:41:06.041+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mongo_test.py
[2024-11-25T07:41:06.050+0000] {logging_mixin.py:190} INFO - [2024-11-25T07:41:06.047+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mongo_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mongo_test.py", line 38, in <module>
    mongo_uri = Variable.get("MONGO_URI")
                ^^^^^^^^
NameError: name 'Variable' is not defined. Did you mean: 'callable'?
[2024-11-25T07:41:06.052+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mongo_test.py
[2024-11-25T07:41:06.079+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mongo_test.py took 0.047 seconds
